server {
    listen 80;
    server_name api.seventech.local;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.seventech.local;

    ssl_certificate     /etc/ssl/certs/seventech.crt;
    ssl_certificate_key /etc/ssl/private/seventech.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://orb-server:80;

        include /etc/nginx/proxy.conf;
    }
}

server {
    listen 80;
    server_name seventech.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name seventech.local;

    ssl_certificate     /etc/ssl/certs/seventech.crt;
    ssl_certificate_key /etc/ssl/private/seventech.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        include /etc/nginx/cors.conf;
        proxy_pass http://jclyonsenterprises:3001;
        include /etc/nginx/proxy.conf;
    }
}